# -*- coding: utf-8 -*-
"""
PlanX Suitability Lab Submodule
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Core Multi-Criteria Decision Analysis (MCDA) mathematical engines,
including reclassification, normalization, and weighted linear combination.
"""

from .facility import (
    capacitated_location_allocation,
    evaluate_tod_node_suitability,
    ev_fleet_charging_location_allocation,
    greedy_lscp,
    greedy_mclp,
    greedy_p_median,
    mclp_distance_decay,
    pareto_facility_location,
    tod_spatial_diversity_index,
)
from .mcda import (
    aras_method,
    copras_method,
    edas_method,
    electre_i_method,
    electre_iii_method,
    fuzzy_copras_method,
    fuzzy_topsis_method,
    fuzzy_vikor_method,
    if_vikor_method,
    ivif_topsis_method,
    marcos_method,
    neutrosophic_waspas_method,
    picture_fuzzy_topsis,
    rough_topsis_method,
    mcda_sensitivity_monte_carlo,
    normalize_array,
    promethee_ii_method,
    spotis_method,
    topsis_method,
    vikor_method,
    waspas_method,
    weighted_linear_combination,
)
from .weights import (
    ahp_weights,
    bwm_weights,
    critic_weights,
    decision_matrix_from_layers,
    dematel_method,
    entropy_weights,
    fucom_weights,
    fuzzy_ahp_weights,
    pca_weights,
)

__all__ = [
    "normalize_array",
    "weighted_linear_combination",
    "topsis_method",
    "vikor_method",
    "promethee_ii_method",
    "electre_i_method",
    "electre_iii_method",
    "aras_method",
    "copras_method",
    "edas_method",
    "marcos_method",
    "waspas_method",
    "fuzzy_topsis_method",
    "fuzzy_vikor_method",
    "mcda_sensitivity_monte_carlo",
    "greedy_mclp",
    "mclp_distance_decay",
    "pareto_facility_location",
    "greedy_p_median",
    "greedy_lscp",
    "capacitated_location_allocation",
    "ahp_weights",
    "bwm_weights",
    "fuzzy_ahp_weights",
    "fucom_weights",
    "dematel_method",
    "decision_matrix_from_layers",
    "entropy_weights",
    "critic_weights",
    "pca_weights",
    "evaluate_tod_node_suitability",
    "spotis_method",
    "ev_fleet_charging_location_allocation",
    "ivif_topsis_method",
    "neutrosophic_waspas_method",
    "tod_spatial_diversity_index",
    "if_vikor_method",
    "rough_topsis_method",
    "fuzzy_copras_method",
    "picture_fuzzy_topsis",
]
